image: node:11.15.0

# add 'node_modules' to cache for speeding up builds
cache:
  paths:
    - node_modules/ # Node modules and dependencies


before_script:
    #- apt-get update && apt-get install -y \rsync 
    #- npm i docsify-cli -g

pages:
  script:
        # - apt-get update 
        # - apt-get install build-essential
        # - apt-get update && apt-get install -y \yum


    #- docsify init ./public

    # The build directory is created based on the value set for projectName in
    # website/siteConfig.js. If you change it there, you need to change it here
    # as well.
    #- pwd
    #- ls -a

    - mkdir .public
    - cp -r docs/. public
    - mv .public public


    
  artifacts:
    paths:
      - public
  only:
    - master

